language: java
before_install:
  - echo "<settingsSecurity><master>$MAVEN_MASTER_PASSWORD</master></settingsSecurity>">$HOME/.m2/settings-security.xml
  - cp .travis.settings.xml $HOME/.m2/settings.xml
script: mvn clean compile package -X
jdk: openjdk11
os: linux
